/**
 * Created with JetBrains WebStorm.
 * User: LXJ
 * Date: 13-5-14
 * Time: 下午5:27
 * To change this template use File | Settings | File Templates.
 */
var lay={
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    random:1,
    cols:[
        {
            width:45,
            random:1,
            rows:[
                {
                    height:50,
                    random:1,
                    cols:[
                        {
                            width:30
                        },
                        {
                            width:30,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:40
                        }
                    ]
                },
                {
                    height:50,
                    rows:[
                        {
                            height:30
                        },
                        {
                            height:30,
                            cols:[
                                {
                                    width:40
                                },
                                {
                                    width:60
                                }
                            ]
                        },
                        {
                            height:40
                        }
                    ]
                }
            ]
        },
        {
            width:55,
            rows:[
                {
                    height:30
                },
                {
                    height:40
                },
                {
                    height:30,
                    cols:[
                        {
                            width:30
                        },
                        {
                            width:30,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:40
                        }
                    ]
                }
            ]
        }
    ]
};

var lay2={
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    rows:[
        {
            height:45,
            rows:[
                {
                    height:50,
                    cols:[
                        {
                            width:20
                        },
                        {
                            width:60,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:20
                        }
                    ]
                },
                {
                    height:50,
                    cols:[
                        {
                            width:35
                        },
                        {
                            width:30,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:35
                        }
                    ]
                }
            ]
        },
        {
            height:55,
            cols:[
                {
                    width:30,
                    rows:[
                        {
                            height:35
                        },
                        {
                            height:25
                        },
                        {
                            height:40
                        }
                    ]
                },
                {
                    width:44
                },
                {
                    width:26
                }
            ]
        }
    ]
}

var lay3={
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    rows:[
        {
            height:45,
            rows:[
                {
                    height:50,
                    cols:[
                        {
                            width:30
                        },
                        {
                            width:30,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:40
                        }
                    ]
                },
                {
                    height:50,
                    rows:[
                        {
                            height:30,
                            cols:[
                                {
                                    width:30
                                },
                                {
                                    width:15
                                },
                                {
                                    width:25
                                },
                                {
                                    width:10
                                },
                                {
                                    width:20
                                }
                            ]
                        },
                        {
                            height:30,
                            cols:[
                                {
                                    width:20
                                },
                                {
                                    width:20
                                },
                                {
                                    width:40
                                },
                                {
                                    width:20
                                }
                            ]
                        },
                        {
                            height:40,
                            cols:[
                                {
                                    width:40
                                },
                                {
                                    width:30
                                },
                                {
                                    width:30
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            height:55,
            rows:[
                {
                    height:30,
                    cols:[
                        {
                            width:30
                        },
                        {
                            width:30,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:40
                        }
                    ]
                },
                {
                    height:30,
                    cols:[
                        {
                            width:20
                        },
                        {
                            width:30
                        },
                        {
                            width:25
                        },
                        {
                            width:15
                        },
                        {
                            width:10
                        }
                    ]
                },
                {
                    height:40,
                    cols:[
                        {
                            width:30
                        },
                        {
                            width:35
                        },
                        {
                            width:20
                        },
                        {
                            width:15
                        }
                    ]
                }
            ]
        }
    ]
};

var lay4={
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    rows:[
        {
            height:55,
            cols:[
                {
                    width:65,
                    rows:[
                        {
                            height:50
                        },
                        {
                            height:50
                        }
                    ]
                },
                {
                    width:35,
                    cols:[
                        {
                            width:60,
                            rows:[
                                {
                                    height:30
                                },
                                {
                                    height:30
                                },
                                {
                                    height:40
                                }
                            ]
                        },
                        {
                            width:40,
                            rows:[
                                {
                                    height:35
                                },
                                {
                                    height:40
                                },
                                {
                                    height:25
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            height:45,
            rows:[
                {
                    cols:[
                        {
                            width:30,
                            cols:[
                                {
                                    width:50
                                },
                                {
                                    width:50
                                }
                            ]
                        },
                        {
                            width:30,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:40,
                            rows:[
                                {
                                    height:40,
                                    cols:[
                                        {
                                            width:55
                                        },
                                        {
                                            width:45
                                        }
                                    ]
                                },
                                {
                                    height:60,
                                    cols:[
                                        {
                                            width:35
                                        },
                                        {
                                            width:65
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
};
var lay5={
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    random:1,
    rows:[
        {
            height:55,
            random:1,
            cols:[
                {
                    width:65,
                    background:"#690",
                    random:1,
                    rows:[
                        {
                            height:50
                        },
                        {
                            height:50
                        }
                    ]
                },
                {
                    width:35,
                    background:"#960",
                    random:1,
                    cols:[
                        {
                            width:60,
                            random:1,
                            rows:[
                                {
                                    height:30
                                },
                                {
                                    height:30
                                },
                                {
                                    height:40
                                }
                            ]
                        },
                        {
                            width:40,
                            random:1,
                            rows:[
                                {
                                    height:35
                                },
                                {
                                    height:40
                                },
                                {
                                    height:25
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            height:45,
            background:"#c00",
            random:1,
            rows:[
                {
                    cols:[
                        {
                            width:30,
                            random:1,
                            cols:[
                                {
                                    width:50
                                },
                                {
                                    width:50
                                }
                            ]
                        },
                        {
                            width:30,
                            random:1,
                            rows:[
                                {
                                    height:40
                                },
                                {
                                    height:60
                                }
                            ]
                        },
                        {
                            width:40,
                            random:1,
                            rows:[
                                {
                                    height:40,
                                    random:1,
                                    cols:[
                                        {
                                            width:55
                                        },
                                        {
                                            width:45
                                        }
                                    ]
                                },
                                {
                                    height:60,
                                    random:1,
                                    cols:[
                                        {
                                            width:35
                                        },
                                        {
                                            width:65
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
};

var tagData=[
        {"doctitle":"台湾对菲11项制裁或升级 演习展示护渔决心","name":"台湾强硬制裁","url":"/70/70874/1.html"},
        {"doctitle":"海南受害女生：校长拿安全套称防止我们怀孕","name":"海南校长和六名女生","url":"/70/70959/1.html"},
        {"doctitle":"台湾对菲11项制裁或升级 演习展示护渔决心","name":"菲11项制裁","url":"/70/70927/1.html"},
        {"doctitle":"广电总局确认整治抗战雷剧 过度娱乐化将停播","name":"广电整治抗战雷剧","url":"/70/70929/1.html"},
        {"doctitle":"电话诈弹威胁航班嫌疑人被捕 为26岁内蒙古人","name":"威胁深航航班","url":"/70/70869/1.html"},
        {"doctitle":"外媒称中国农民工“临时夫妻”人数或超十万","name":"临时夫妻超十万","url":"/70/70871/1.html"},
        {"doctitle":"中国南方多省遭强降雨袭击 已造成33人死12人失踪","name":"中国南方强降雨","url":"/70/70925/1.html"},
        {"doctitle":"达赖《自焚指导书》曝光： 规范化系统化自焚","name":"达赖操纵自焚","url":"/70/70873/1.html"},
        {"doctitle":"贝克汉姆宣布本赛季末退役：是时候结束足球生涯","name":"贝克汉姆今夏退役","url":"/70/70997/1.html"},
        {"doctitle":"今日之声：艳遇佛抱着的不是女人是智慧","name":"艳遇佛","url":"/70/70998/1.html"},
        {"doctitle":"香港轻轨列车出轨续：乘客称列车转弯时车速很快","name":"香港轻轨","url":"/70/70972/1.html"},
        {"doctitle":"西藏尼玛县今日发生3次地震 最大震级5.2级","name":"西藏尼玛地震","url":"/70/70822/1.html"},
        {"doctitle":"山东德州一直升机被劫持 事件原因系经济纠纷","name":"直升机被劫持","url":"/70/70824/1.html"},
        {"doctitle":"广东遭特大暴雨袭击引发洪灾 致18人死15人失踪","name":"广东遭特大暴雨","url":"/70/70906/1.html"},
        {"doctitle":"戛纳国际电影节开幕 红毯仪式上众星云集（图)","name":"戛纳电影节开幕","url":"/70/70809/1.html"},
        {"doctitle":"比尔&middot;盖茨重当首富(图)","name":"比尔盖茨 首富","url":"/70/70990/1.html"},
        {"doctitle":"24岁猝死 白领加班再成焦点(图)","name":"加班一月猝死","url":"/70/70902/1.html"},
        {"doctitle":"马琳：胜负不影响对未来的选择","name":"马琳无缘大满贯","url":"/70/70963/1.html"},
        {"doctitle":"坑面女治愈后产下健康男婴(组图)","name":"坑面女","url":"/71/71000/1.html"},
        {"doctitle":"国办：高校毕业生招聘禁止设年龄户籍等限制","name":"毕业生招聘 限制","url":"/70/70870/1.html"},
        {"doctitle":"19岁大一学生年入1500万(图)","name":"19岁学生年入1500万","url":"/70/70951/1.html"},
        {"doctitle":"知情人称刘铁男硕士学历系由情妇帮忙伪造","name":"刘铁男情妇","url":"/70/70806/1.html"},
        {"doctitle":"众好友请缨加盟许茹芸个唱","name":"许茹芸个唱","url":"/70/70954/1.html"},
        {"doctitle":"中国籍“袭胸男”在新加坡被判鞭刑","name":"新加坡鞭刑 “袭胸男”","url":"/70/70827/1.html"},
        {"name":"沈阳飞机坠毁","url":"/70/70832/1.html"},
        {"name":"高桥石化","url":"/70/70935/1.html"},
        {"name":"王烁打人道歉","url":"/70/70797/1.html"},
        {"name":"希拉里自曝双性恋","url":"/70/70789/1.html"},
        {"name":"青川地震","url":"/70/70794/1.html"},
        {"name":"多省现UFO","url":"/70/70757/1.html"},
        {"name":"仲祖文文章","url":"/70/70907/1.html"},
        {"name":"新非典","url":"/70/70754/1.html"},
        {"name":"领馆现不明粉末","url":"/70/70756/1.html"},
        {"name":"厦门暴雨","url":"/70/70826/1.html"},
        {"name":"琉球共和国","url":"/70/70802/1.html"},
        {"name":"安吉丽娜切除双乳","url":"/70/70653/1.html"},
        {"name":"姜志刚任组织部长","url":"/70/70820/1.html"},
        {"name":"叙反对派“挖心生吃”","url":"/70/70768/1.html"},
        {"name":"公交 易走光座位","url":"/70/70840/1.html"},
        {"name":"托雷斯被扯开球裤","url":"/70/70849/1.html"},
        {"name":"妮可基德曼","url":"/70/70845/1.html"},
        {"name":"金价再跌","url":"/70/70591/1.html"},
        {"name":"中国大妈被套","url":"/70/70602/1.html"},
        {"name":"女工谈临时夫妻","url":"/70/70717/1.html"},
        {"name":"加纳淘金","url":"/70/70710/1.html"},
        {"name":"免职刘铁男","url":"/70/70600/1.html"},
        {"name":"奥美中国","url":"/70/70676/1.html"},
        {"name":"最难就业季","url":"/70/70599/1.html"},
        {"name":"丁薛祥","url":"/70/70815/1.html"},
        {"name":"凌成兴","url":"/70/70801/1.html"}
    ];
